config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'

  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/secret',  to: 'static_pages#secret'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password

  class << self
      # Returns the hash digest of the given string.
      def digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end

      # Returns a random token.
      def new_token
        SecureRandom.urlsafe_base64
      end
  end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
    update_attribute(:remember_digest, nil)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      remember user
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

 def destroy
    log_out if logged_in?
    redirect_to root_url
 end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def secret
    if ! logged_in?
      flash[:danger] = 'hey login-toi pour y accéder'
      redirect_to login_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    if @user.id != current_user.id
     flash[:danger] = 'vilain garnement ... tu vas finir par te faire taper sur les doigts !'
     redirect_to root_path
    end
  end

  def new
    @user = User.new
  end

  def create
     @user = User.new(user_params)
     if @user.save
     log_in @user
      flash[:success] = "Bienvenue dans l'app Secrete Moussaillon!"
      redirect_to @user
         else
       render 'new'
     end
  end

   private

     def user_params
       params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation)
     end

     def edit
        @user = User.find(params[:id])
     end

     def destroy
      User.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to root_url
     end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
   session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
      redirect_to(session[:forwarding_url] || default)
      session.delete(:forwarding_url)
  end

    # Stores the URL trying to be accessed.
    def store_location
      session[:forwarding_url] = request.original_url if request.get?
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
   image_tag(gravatar_url, alt: user.name, class: "gravatar")
 end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   '/' %></li>
            <li><%= link_to "Log in", '/login' %></li>
          </ul>
        </nav>
      </div>
    </header>
      <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
<h1>Secret site, le site du secret ultime</h1>
  <p>Hey bienvenue!</p>

  <p><%= link_to "Connecte toi pour accéder à la page secrète!", login_path, class: "btn btn-lg btn-primary" %></p>
</div>

app/views/static_pages/secret.html.erb
<% provide(:title, @user.name) %>
<div class="center jumbotron">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <p>Bienvenue sur LA page secrète <%= @user.name %> </p>
      </h1>
      <p> Ton adresse email <%= @user.email %> est maintenant aux mains de la CIA/NSA/Nasa etc.. ainsi que toute ta vie, muahahahaha!</p>

    <p>Il est temps pour toi de connaitre la vérité : <br>
      La terre est plate pauvre humain insignifiant!</p>
      <img src="https://www.terresacree.org/actualites/fichiers/images/2017-02/1486932640-t8d.jpg">
  <br>
  <%= link_to "Log out", logout_path, method: :delete, :class=> "btn btn-lg btn-primary" %>
  </section>
</div>

app/views/users/edit.html.erb
<% provide(:title, "User / Update") %>
<% provide(:button_text, "Mettre à jour") %>
<h1>Mise à jour du profil</h1>
<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" class="btn btn-primary">Changer</a>
    </div>
  </div>
  <div class="col-md-3">
    <%= image_tag("thp-big.png", alt: "The Hacking Project Logo", class: "thp") %>
    <p>
      <br>
      <%= link_to "Supprimer", @user, method: :delete, data: { confirm: "T'es sûr ?" }, class: "btn btn-primary" %>
    </p>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="center jumbotron">
  <div class="col-md-6 col-md-offset-3">
      <h1>Créer ton compte :D</h1>
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Let's go!", class: "btn btn-primary" %>
    <% end %>
      <p>Tu as un compte? <%= link_to "Connecte toi pour accéder à la page secrète!", login_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="center jumbotron">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <p>Bienvenue sur LA page secrète <%= @user.name %> </p>
      </h1>
      <p> Ton adresse email <%= @user.email %> est maintenant aux mains de la CIA/NSA/Nasa etc.. ainsi que toute ta vie, muahahahaha!</p>

    <p>Il est temps pour toi de connaitre la vérité : <br>
      La terre est plate pauvre humain insignifiant!</p>
      <img src="https://www.terresacree.org/actualites/fichiers/images/2017-02/1486932640-t8d.jpg">
  <br>
  <%= link_to "Log out", logout_path, method: :delete, class: "btn btn-lg btn-primary" %>
  </section>
</div>